### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by airk42** [ANIME-AnimeCoin/AnimeCoin#1]
- [x] Replace github links: 
  - https://github.com/zcash/zcash for https://github.com/ANIME-AnimeCoin/AnimeCoin
- [x] Add Anime copyright line to copyright notes:
  - Copyright (c) 2018 The AnimeCoin developers
- [x] Replaces emails @z.cash for something AnimeCoin specific (ask Jeff or Gareth)
- [x] Replace zcash in the documentation:
  - [x] Readme
  - [x] INSTALL
  - [x] ...
  - [x] Doc/*
- [x] Replace zcash in the comments
- [x] Replace zcash in the outputs - logs, error messages and such

**Comment by akx20000a** [comment]
@airk42 Hi! Seeing you again from ZClassic 👍

**Comment by akx20000a** [comment]
@airk42 Do we need to use ZCash fork?
